version: '3.3'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    
    
    image: amulyaprasanth/langgenie_backend_ollama

  app:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'

    image: amulyaprasanth/langgenie_frontend_ollama



  