version: "3.3"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

    image: amulyaprasanth/langgenie_backend

  app:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

    image: amulyaprasanth/langgenie_frontend
