name: Build and Push Docker Image

on:
    push:
        branches: [ main ]


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repositor
              uses: actions/checkout@v4

            - name: login docker
              uses: docker/login-action@v4
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: build docker image
              run: |
                docker build -t amulyaprasanth/langgenie_backend:latest backend

            - name: Push Docker Image to Hub
              run: |
                    docker push your-dockerhub-username/your-image-name:latest
                    docker push your-dockerhub-username/your-image-name:${{ github.sha }}
            