name: Build and Push Frontend and Backend Docker Images

on:
    push:
        branches: [ main ]

jobs:
    build-and-push-images:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repositor
              uses: actions/checkout@v4

            - name: login docker
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: build docker images
              run: |
                docker build -t amulyaprasanth/langgenie_backend:latest backend
                docker build -t amulyaprasanth/langgenie_frontend:latest frontend

            - name: Push Docker Images to Hub
              run: |
                    docker push amulyaprasanth/langgenie_backend:latest
                    docker push amulyaprasanth/langgenie_frontend:latest

            